name: flutter_map_marker_cluster
description: A Dart implementation of Leaflet.makercluster for Flutter apps.
  Provides beautiful animated marker clustering functionality for flutter_map.
version: 1.3.5
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

homepage: https://github.com/lpongetti/flutter_map_marker_cluster

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: 7.0.0-dev.1
  flutter_map_marker_popup:
    git:
      url: git@github.com:OutdoreUK/flutter_map_marker_popup.git
      ref: master
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
